version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass